### ISSUE TITLE
Affiliate page rework

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.id#32]
Remake this https://www.starknet.id/affiliates/individual-program page with @Kevils design (not ready yet)

**Comment by Kevils** [comment]
Figma link for affiliate page redesign : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID-design?type=design&node-id=1746%3A5576&mode=design&t=vf2OgCJUnOT0V9ZK-1
