### ISSUE TITLE
Affiliate calculator

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.id#36]
![image](https://github.com/starknet-id/starknet.id/assets/144677881/6b111513-5a97-4883-9449-6e9a33223887)

Link : https://goerli.starknet.id/affiliates/individual-program

Modify naming of the second slider with something like : Each referral will refer

Modify the calculator.

**Comment by Th0rgal** [comment]
![telegram-cloud-photo-size-4-5845943797370961751-y](https://github.com/starknet-id/starknet.id/assets/41830259/9796ed9c-112b-43e2-b8e2-294887db8304)
