### ISSUE TITLE
Switch the default image in the "opportunity section" of the affiliate page to the PFP

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.id#65]
File : https://we.tl/t-JCknwmwfYv

1 - Modify this image of this page https://starknet.id/affiliates/individual-program by the second one. The image is available with the wetransfer link.

Current : 
![image](https://github.com/starknet-id/starknet.id/assets/144677881/2c0cac42-f790-4c18-b48e-f368d5fb0e45)

New : 
![image](https://github.com/starknet-id/starknet.id/assets/144677881/9841c0cf-b3d1-499e-a264-cccd5e52951d)

**Comment by Favvie** [comment]
May I handle this issue?

**Comment by 0xdevcollins** [comment]
Can I jump on this task?

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by pheobeayo** [comment]
May I take this issue on?
 ETA I day

**Comment by mayasimi** [comment]
Could I take over this issue?

**Comment by petersdt** [comment]
am a frontend developer.

kindly assign me this issue 

ETA <= 24hrs

**Comment by NueloSE** [comment]
Can I handle this task?

**Comment by 0xDeon** [comment]
I'd love to give this a go.
I am a Full-Stack Developer

ETA: < 1 hr

**Comment by deeseeker** [comment]
Can I jump on this task?

**Comment by hossamanany** [comment]
May I take care of this?

**Comment by suhas-sensei** [comment]
Could I take a shot at this? I will do as requested.

**Comment by OWK50GA** [comment]
I am Wilfrid, a Frontend Web Developer.
Can I take this issue?
I can deliver this within 3 hours with the image for replacement already made available.

**Comment by SudiptaPaul-31** [comment]
Would love to contribute to this issue

My name is Sudipta Paul having expertise in full stack and blockchain for around 1.5 years and is an active contributor to starknet.

My approach:

Will first start by going to the file and locate the image line and change the image as per the one given. After that making sure its properly aligned or fit or not if needed any css properties will apply and at last before making a pr a proper testing of it.

**Comment by dadadave80** [comment]
I’d like to help with this.

**Comment by Khemmie-Ray** [comment]
Can I work on this?

**Comment by akintola4** [comment]
Can I try solving this issue? i would love to work on this task and be able to do it if given

**Comment by Yunusabdul38** [comment]
I'd love to work on this!
and make sure it meets the requirements

**Comment by Steph3097** [comment]
Hey @ Kevils! I'm Sttef from Dojo Coding Costa Rica. This is my first OD Hack and this would be my first contribution, I’m a Front end dev with over 5 years of experience. I will change the image for the desired one. May I work on this one ?

**Comment by deeseeker** [comment]
Thanks. the link to the site is broken. @Kevils

**Comment by deeseeker** [comment]
@Kevils  I have submitted a PR for the issue. if you want me to blend the new image to have the same background as the opportunity section, you can include that in your review.

Thanks for allowing me to work on the issue

**Comment by 0xDeon** [comment]
On it

**Comment by deeseeker** [comment]
@Kevils I already submitted a PR for this task.

**Comment by fricoben** [comment]
Mistakely reassigned but was done
